# Generated by Django 6.0.4 on 2026-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=255, verbose_name='Página Acessada')),
                ('tempo_permanencia', models.IntegerField(verbose_name='Tempo (Segundos)')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Registro de Acesso',
                'verbose_name_plural': 'Análise de Tráfego',
            },
        ),
    ]
