"""
Django settings for ejcon_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_HEADER": "Painel EJCON", # O texto que aparece lá no topo esquerdo
    "SITE_TITLE": "Administração EJCON", # O texto que aparece na aba do navegador
    "SITE_SYMBOL": "rocket_launch",  # Um ícone do Google Material Symbols para ficar ao lado do nome
    "SIDEBAR": {
        "show_search": True,  # Adiciona uma barra de pesquisa no topo do menu
        "show_all_applications": False, # Esconde o menu padrão feio para usar apenas este customizado
        "navigation": [
            {
                "title": "Administração do Sistema",
                "separator": True,  # Isso cria a linha divisória clara que você pediu!
                "items": [
                    {
                        "title": "Usuários",
                        "icon": "person",  # Nome do ícone no Google Material Symbols
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Grupos",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": "Gestão EJCON",
                "separator": True,  # Separa o Core da Autenticação
                "items": [
                    {
                        "title": "Soluções",
                        "icon": "article",
                        "link": reverse_lazy("admin:core_solucao_changelist"),
                    },
                    {
                        "title": "Valores",
                        "icon": "diamond",
                        "link": reverse_lazy("admin:core_valor_changelist"),
                    },
                    {
                        "title": "Membros da Equipe",
                        "icon": "badge",
                        "link": reverse_lazy("admin:core_membroequipe_changelist"),
                    },
                    {
                        "title": "Leads",
                        "icon": "campaign",
                        "link": reverse_lazy("admin:core_lead_changelist"),
                    },
                    {
                        "title": "Estatísticas",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:core_estatistica_changelist"),
                    },
                    {
                        "title": "Registro Acessos",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:core_registroacesso_changelist"),
                    },
                ],
            },
        ],
    },
    "COLORS": {
        "primary": {
            "50": "#fff8f0",
            "100": "#ffefdb",
            "200": "#ffdbad",
            "300": "#ffc17a",
            "400": "#ffa242",
            "500": "#ff7f00",  # O Laranja principal da EJCON
            "600": "#ed6700",
            "700": "#c44c00",
            "800": "#9c3b00",
            "900": "#7d3103",
            "950": "#441500",
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o%!j(1+mpuzz5-jk$fb7rf*fsv9e5&c+utw@(5am-yz!%(ena&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",  # Opcional: filtros modernos
    "unfold.contrib.forms",    # Opcional: formulários modernos
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ejcon_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ejcon_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuração Padrão do CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
    },
    'extends': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'underline', '|', 'bulletedList', 'numberedList', '|', 'insertImage', 'blockQuote'],
    }
}

